name: hfut_hole_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  dio: ^5.4.0
  fluent_ui: ^4.8.1
  flutter:
    sdk: flutter
  flutter_gen: ^5.3.2
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod: ^2.4.9
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: false
