name: hfut_hole_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  dio: ^5.4.0
  envied: ^0.5.2
  fluent_ui: ^4.8.1
  flutter:
    sdk: flutter
  flutter_gen: ^5.3.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  riverpod: ^2.4.9
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  envied_generator: ^0.5.2
  json_serializable: ^6.7.1
  freezed: ^2.4.5

flutter:
  uses-material-design: false
